#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/runtime:6.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["TwitterStream.ConsoleApp/TwitterStream.ConsoleApp.csproj", "TwitterStream.ConsoleApp/"]
COPY ["TwitterStream.Core/TwitterStream.Core.csproj", "TwitterStream.Core/"]
COPY ["TwitterStream.Data/TwitterStream.Data.csproj", "TwitterStream.Data/"]
COPY ["TwitterStream.Interfaces/TwitterStream.Interfaces.csproj", "TwitterStream.Interfaces/"]
COPY ["TwitterStream.Reporting/TwitterStream.Reporting.csproj", "TwitterStream.Reporting/"]
COPY ["TwitterStream.Service/TwitterStream.Service.csproj", "TwitterStream.Service/"]
RUN dotnet restore "TwitterStream.ConsoleApp/TwitterStream.ConsoleApp.csproj"
COPY . .
WORKDIR "/src/TwitterStream.ConsoleApp"
RUN dotnet build "TwitterStream.ConsoleApp.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "TwitterStream.ConsoleApp.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "TwitterStream.ConsoleApp.dll"]